#!/bin/bash
FOREVER="/usr/local/bin/forever"
BPATH="/home/pi/activServer/"
ERR="error.log"
LOG="forever.log"
OUT="out.log"
APP="app.js"
MINUP="10000"
SPSLEEP="2000"

$FOREVER start -v -a --minUptime $MINUP --spinSleepTime $SPSLEEP -e $BPATH$ERR $BPATH$APP
